plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  SuggestExtensions: false

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/casdoor-ruby-sdk.rb

Metrics:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - spec/integration_spec.rb

Naming/PredicateMethod:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false
